from pptx import Presentation
from pptx.util import Inches, Pt
import os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_DIR = os.path.join(BASE, "outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "deepfake_detector_presentation.pptx")

prs = Presentation()
blank_slide_layout = prs.slide_layouts[5]

# Helper to add title + bullet slide
def add_title_bullets(title, bullets, notes=None):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    body = slide.shapes.placeholders[1].text_frame
    body.clear()
    for i, b in enumerate(bullets):
        p = body.add_paragraph() if i>0 else body.paragraphs[0]
        p.text = b
        p.level = 0
    if notes:
        slide.notes_slide.notes_text_frame.text = notes
    return slide

# 1 Title
slide = prs.slides.add_slide(prs.slide_layouts[0])
slide.shapes.title.text = "Deepfake Detector"
slide.placeholders[1].text = "Short, crisp project overview and demo outputs"
slide.notes_slide.notes_text_frame.text = "Author: autogenerated by tools/generate_presentation.py\nUse this as a base for presentations."

# 2 Problem
add_title_bullets("Problem", [
    "Deepfakes and synthetic media erode trust in visual content.",
    "Need fast, explainable detection for images and CCTV footage.",
], notes="Explain real-world risks: misinformation, security breaches.")

# 3 Dataset
add_title_bullets("Dataset", [
    "Raw dataset: /dataset/ (real & fake folders)",
    "Processed crops saved to /dataset/processed via `train.py` preprocessing",
    "Includes image frames and sampled video frames"
], notes="Mention typical dataset sizes and sampling strategy.")

# 4 Model Architecture
add_title_bullets("Model Architecture", [
    "Custom CNN: 4 conv blocks -> AdaptiveAvgPool -> Dense (2 classes)",
    "Input: 224x224 RGB crops; Output: real vs fake probabilities",
], notes="Architecture matches `ForensicEngine` classifier in repo.")

# 5 Training
add_title_bullets("Training", [
    "Preprocess: face extraction & center crops (see `train.py`).",
    "Augmentations: flips, rotations, color jitter; batch=16; epochs=15",
    "Loss: weighted CrossEntropy to handle class imbalance"
], notes="State best practices and compute requirements briefly.")

# 6 Forensic Engine
add_title_bullets("Forensic Engine", [
    "Spatial analysis: edge blending, lighting asymmetry, texture coherence",
    "Spectral analysis: FFT radial profiles and 10x10 heatmap",
    "Temporal flow: optical flow-based inconsistency detection"
], notes="These methods provide explainable cues alongside DL scores.")

# 7 CCTV Engine
add_title_bullets("CCTV Summarizer", [
    "Samples video at ~5 FPS, computes motion profile and activity events",
    "Detects objects (people, vehicles) and saves keyframe crops",
    "Produces timeline events, threat scoring, and executive brief"
], notes="Good for surveillance and incident triage.")

# 8 Demo Outputs (images)
slide = prs.slides.add_slide(blank_slide_layout)
slide.shapes.title.text = "Demo Outputs"
left = Inches(0.5)
top = Inches(1.5)
img_w = Inches(4.3)
img_h = Inches(3.0)

# Example images from backend/static/sampled/cctv
examples = [
    os.path.join(BASE, "backend", "static", "sampled", "cctv", "0c19600b-e8d4-42ca-9fef-484d1fac5b3d", "event_EV_01_full.jpg"),
    os.path.join(BASE, "backend", "static", "sampled", "cctv", "0c19600b-e8d4-42ca-9fef-484d1fac5b3d", "event_EV_02_full.jpg"),
]

for i, img in enumerate(examples):
    if os.path.exists(img):
        tx = left + Inches(i * 4.6)
        slide.shapes.add_picture(img, tx, top, width=img_w, height=img_h)

slide.notes_slide.notes_text_frame.text = "Example CCTV keyframes and crops saved by the `CctvEngine` (see backend/static/sampled/cctv/... )."

# 9 Results & Metrics
add_title_bullets("Results & Metrics", [
    "Training loop saves best checkpoint to /models/deepfake_classifier.pth",
    "Use validation split (80/20) to track generalization",
    "Combine Forensic + DL scores for robust decisions"
], notes="Insert numeric results here after running experiments.")

# 10 Conclusion & Next Steps
add_title_bullets("Conclusion & Next Steps", [
    "Built a hybrid forensic + deep learning pipeline for anomaly detection",
    "Next: expand dataset, quantify metrics, deploy inference API",
    "Consider UI improvements and model distillation for edge use"
], notes="Offer to add more slides or refine phrasing on request.")

# Save presentation
prs.save(OUTPUT_PATH)
print(f"Presentation saved to: {OUTPUT_PATH}")
